In [1]:
from IPython.display import HTML

HTML('''<script> $('div .input').hide()''')

In [11]:
import numpy as np
import pandas as pd

In [12]:
print('hello')

hello


In [13]:
from sklearn import datasets

In [14]:
import seaborn as sns

iris = sns.load_dataset('iris')
iris.head() 

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
a=np.arange(25).reshape(5,5)

In [18]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
np.array(a[1],a[2])


TypeError: data type not understood

In [26]:
a[a<3]

array([0, 1, 2])

In [27]:
a<3

array([[ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [28]:
 b=a<3

In [29]:
b

array([[ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [30]:
a=np.array([1,2,3])

In [31]:
a[2]

3

In [38]:
a[1]

2